name: mlggeo2024_aobuoypredict
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - xarray
  - netCDF4
  - dask
  - scipy
  - requests
  - beautifulsoup4
  - statsmodels
  - pip
  - pip:
      - tensorflow
      - keras
      - h5py